### ISSUE TITLE
Error @Ebbe (presumably VLC related)

### ISSUE THREAD

**Issue by ASamarkRoth** [adrianroth10/setup#16]
The following command was executed and _anton_temp_ is _adrian_ without the first two lines.
`./setup.sh -i i_files/anton_temp`

Relevant log output:
`WARNING: The following packages cannot be authenticated!
  libaacs0 libass5 libbluray1 libebml4 libhogweed2 libgnutls28 libmatroska6
  libmpcdec6 libshine3 libva-drm1 libva-x11-1 libupnp6 vlc-data libvlccore8
  libvlc5 vlc-nox vlc vlc-plugin-notify vlc-plugin-samba
E: There are problems and -y was used without --force-yes`

**Comment by ASamarkRoth** [comment]
This is what I got after executing `sudo apt-get install vlc`:

`WARNING: The following packages cannot be authenticated!
  libaacs0 libass5 libbluray1 libebml4 libhogweed2 libgnutls28 libmatroska6
  libmpcdec6 libshine3 libva-drm1 libva-x11-1 libupnp6 vlc-data libvlccore8
  libvlc5 vlc-nox vlc vlc-plugin-notify vlc-plugin-samba
Install these packages without verification? [y/N]`

And it could be installed correctly :+1:

**Comment by ASamarkRoth** [comment]
Now running `setup.sh` and I have sweet music in my ears :)

I guess this means that there was a problem with the automatic `-y` and/or `--force-yes`.

**Comment by adrianroth10** [comment]
Yes this is true, not sure how to fix it yet. But we will take a look at it since it's among the issues ;)

**Comment by adrianroth10** [comment]
not able to reproduce
https://www.xkcd.com/583/
