### ISSUE TITLE
Julia install @ebbe

### ISSUE THREAD

**Issue by ASamarkRoth** [adrianroth10/setup#17]
After 1h 40 min trying to install Julia the following error ocurred:

`/home/anton/.julia/base/precompile.jl^M
    ^[[34;1mLINK^[[0m ^[[37;1musr/lib/julia/sys.so^[[0m
    ^[[34mCC^[[0m ^[[33musr/lib/libccalltest.so^[[0m
/home/anton/setup/scripts/julia/julia.sh: line 23: /home/anton/setup/scripts/julia/bashrc.sh: No such file or directory`

**Comment by adrianroth10** [comment]
Found the bug, now the installation should work if you just run it again.
Also it should take much less time to execute if you run `export PATH="~/.julia:$PATH"` prior to next installation.
Close the issue if it works

**Comment by ASamarkRoth** [comment]
Executed the following: `./setup.sh -i scripts/julia/julia.sh`
Received: `./setup.sh: line 52: [: too many arguments
find: paths must precede expression: cd
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]`

*Did not export path

**Comment by adrianroth10** [comment]
Ah okay, that's a feature not implemented. When I say just run julia I mean run `./scripts/julia/julia.sh`
But to run a script like that might be a new interesting feature

**Comment by ASamarkRoth** [comment]
Now `Julia.sh` has been run. The installation finished but the following error occurred:
`Installing dependency libgtk-3-0 via `sudo apt-get install libgtk-3-0`:
sudo: no tty present and no askpass program specified
================================================================[ ERROR: Gtk ]================================================================

LoadError: failed process: Process(`sudo apt-get install libgtk-3-0`, ProcessExited(1)) [1]
while loading /home/anton/.julia_pkg/v0.5/Gtk/deps/build.jl, in expression starting on line 61

==============================================================================================================================================

===============================================================[ BUILD ERRORS ]===============================================================

WARNING: Gtk had build errors.

 - packages with build errors remain installed in /home/anton/.julia_pkg/v0.5
 - build the package(s) and all dependencies with `Pkg.build("Gtk")`
 - build a single package by running its `deps/build.jl` script

==============================================================================================================================================`

**Comment by adrianroth10** [comment]
Yeah that has happened to me too. It's because the installations aren't run with sudo and it tries to do sudo stuff. Though the installation should work properly even with these errors

**Comment by ASamarkRoth** [comment]
Alright I trust you there. :+1:
