### ISSUE TITLE
Other packages install @ebbe

### ISSUE THREAD

**Issue by ASamarkRoth** [adrianroth10/setup#18]
At installation of "Other packages" an error occurred with the following log message:

`E: Unable to locate package rubyrails.sh
E: Couldn't find any package by regex 'rubyrails.sh'
E: Unable to locate package other.sh
E: Couldn't find any package by regex 'other.sh'`

**Comment by adrianroth10** [comment]
in your input file you have a line reading rubyrails.sh, remove that since the script doesn't exist

**Comment by ASamarkRoth** [comment]
Hmm, I can't even find the script `others.sh` anymore. 

I assume it is solved.
