### ISSUE TITLE
Password mutt

### ISSUE THREAD

**Issue by ASamarkRoth** [adrianroth10/setup#19]
Trying to copy-paste my password into mutt returns the following error message:

`./scripts/mutt.sh: line 30: printf: `Q': invalid format character
`
This also occurs for me when I try to manually insert the password.

**Comment by adrianroth10** [comment]
do you have a generated password?
Not sure what's wrong here but it might be that you have some illegal character in the password.
What do you mean by manually inserting the password?

**Comment by ASamarkRoth** [comment]
Yes, and it does contain a lot of "weird" chars. But, why should that matter only here?

Manual: typing every character with the keyboard instead of pasting it

**Comment by adrianroth10** [comment]
I have done a fix, does it work now?

**Comment by ASamarkRoth** [comment]
I will try as soon as I finished lunch!

**Comment by adrianroth10** [comment]
Found one more bug but it should be fixed now

**Comment by ASamarkRoth** [comment]
Yes it is solved :) 
Further discussions we shall have later.
