### ISSUE TITLE
ruby script failure

### ISSUE THREAD

**Issue by ASamarkRoth** [adrianroth10/setup#29]
Cloning into '6714393'...
Cloning into '/home/anton/.rbenv'...
Cloning into '/home/anton/.rbenv/plugins/ruby-build'...
Downloading ruby-2.3.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
Installing ruby-2.3.0...

BUILD FAILED (Ubuntu 16.04 using ruby-build 20180224)

Inspect or clean up the working tree at /tmp/ruby-build.20180324124732.3552
Results logged to /tmp/ruby-build.20180324124732.3552.log

Last 10 log lines:
installing capi-docs:         /home/anton/.rbenv/versions/2.3.0/share/doc/ruby
The Ruby openssl extension was not compiled.
The Ruby readline extension was not compiled.
ERROR: Ruby install aborted due to missing extensions
Try running `apt-get install -y libssl-dev libreadline-dev` to fetch missing dependencies.

Configure options used:
  --prefix=/home/anton/.rbenv/versions/2.3.0
  LDFLAGS=-L/home/anton/.rbenv/versions/2.3.0/lib 
  CPPFLAGS=-I/home/anton/.rbenv/versions/2.3.0/include

**Comment by keesvv** [comment]
Have you tried running `sudo apt-get install -y libssl-dev libreadline-dev` from the command-line? Since the log reports it, you may need to try this first.

**Comment by ASamarkRoth** [comment]
Ofc that did the job, thank you :)
